In [26]:
import numpy as np
a = np.zeros(2)
print(a.shape)
a = a + 2
a[1] = 1
a

(2,)


array([ 2.,  1.])

In [28]:
x = np.array([[1,2],[2,3],[3,4]])
print(x.shape)
print(x[0].shape)

print((a * x[1]).shape)
# shape is 2,0 of a, x[1] as well as of the result
# element wise multiplication occurs
# [2*2 = 4 , 1*3 = 3] 
# sum = 7

print((a * x[1]).sum())

# Sum will be same as below three
print("Taking Dot without transposing x[1]",np.dot(a,x[1]))

print("Taking Dot with transposing x[1]",np.dot(a,x[1].T))

print("Matrix Multiplication is also the same", np.matmul(a,x[1]))

(3, 2)
(2,)
(2,)
7.0
Taking Dot without transposing x[1] 7.0
Taking Dot with transposing x[1] 7.0
Matrix Multiplication is also the same 7.0


In [36]:
a = a.reshape(-1,1)

print("With a's shape , sum ans shape change :")
# [
# [2 * 2 , 2*3 ],
# [1 * 2 , 1*3 ]  
# ]
print((a * x[1]))

print((a * x[1]).shape)

print((a * x[1]).sum())


# reshape x1 for matrix operations

print("Dot product :",np.dot(a,x[1].reshape(-1,1).T))
print()

print("Matrix Multiplication is also same: ")
print(np.matmul(a,x[1].reshape(-1,1).T))

With a's shape , sum ans shape change :
[[ 4.  6.]
 [ 2.  3.]]
(2, 2)
15.0
Dot product : [[ 4.  6.]
 [ 2.  3.]]

Matrix Multiplication is also same: 
[[ 4.  6.]
 [ 2.  3.]]
